### PR TITLE
Save login state as cookies

### PR DESCRIPTION
**Pull request by emaohn**
Upon login, sets cookie state loggedIn=true for 2 hours since login (subject to change after integrating with backend for login). For time being this should prevent logout when viewing log details on separate tab.
Cookies cleared on logout and by default when browser is closed.

### CODE REVIEW

**Review by Phil-Nettekoven — CHANGES_REQUESTED** [review]
Looks like it isn't passing the ESLInt check on Jenkins with these errors:

./pages/_app.js
25:32  Error: React Hook "useState" is called conditionally. React Hooks must be called in the exact same order in every component render.  react-hooks/rules-of-hooks
30:37  Error: React Hook "useState" is called conditionally. React Hooks must be called in the exact same order in every component render.  react-hooks/rules-of-hooks
32:49  Error: React Hook "useState" is called conditionally. React Hooks must be called in the exact same order in every component render.  react-hooks/rules-of-hooks
34:18  Error: React Hook "useRouter" is called conditionally. React Hooks must be called in the exact same order in every component render.  react-hooks/rules-of-hooks

**Comment by NewViewDev** [comment]
Not sure if you guys know this already, but "npx next lint -fix" (or it might be --fix, I'm not sure) will fix a lot of these dumb lint errors

**Comment by lilingxi01** [comment]
These issues cannot be fixed automatically. These states are violating the React state rule, which may be breaking some day, and they are not formatting issues, so `npm run lint --fix` will not work.

The issue is that you have to put all return states after the creation of all states (by React rules). I can see that you have an if statement at the beginning of the file, which may result in a return directly before states are all created properly.

You can check here for reference: https://reactjs.org/docs/hooks-rules.html

**Comment by lilingxi01** [comment]
@emaohn : These issues cannot be fixed automatically. The `ClogApp` is violating the React state rule, which may be breaking some day, and they are not formatting issues, so `npm run lint --fix` will NOT work. You need to resolve the following issue manually:

The issue is that you have to put all return states after the creation of all states (by React rules). I can see that you have an if statement at the beginning of the file, which may result in a return directly before states are all created properly.

You can check here for reference: https://reactjs.org/docs/hooks-rules.html

**Review by Phil-Nettekoven — APPROVED** [review]
Great work!

**Pull request merged**
