### PR TITLE
[Tree] Added expand all, changed sample data

### PR DESCRIPTION
**Pull request by nekomi2**

### CODE REVIEW

**Review by lilingxi01 — CHANGES_REQUESTED** [review]
Great progress!! It seems like you are using MUI tree view right now.

- [x] Since we will make a right click menu on a tree item, we need to confirm that MUI tree view allows us to make such "right click" customization (It is doable on a vanilla `<div>` but MUI might not expose those abilities).

- [x] It looks like you miss the "business process instances" hierarchy, which should be located under each business process. You need to at least add it up before next mini-demo if we will present this.

Overall, great job on TreeView!

**Comment by lilingxi01** [comment]
And it seems like your format is not following the requirement of Eslint. If you are using VSCode, you need to download the `Eslint` plugin and open the project by using `front-end` folder as the root folder. In this way, you will see all errors with your formatting. If you are using WebStorm, this behavior should be built-in.

**Comment by nekomi2** [comment]
idk how to get eslint to work yet, I have it on vscode and activated it in front-end, but can't see any warnings when running ``npm run dev``. For now, I added the logs and code for the context menu down the line.

**Comment by nekomi2** [comment]
@limbo-yan can you add the context menu on right click? Right now it's just logging the item right-clicked on to the console. The code is in ``components\business-process\tree\tree-view.js`` ``const contextMenu = (e,source) => console.log( source + 'rightclick')``

**Comment by lilingxi01** [comment]
> idk how to get eslint to work yet, I have it on vscode and activated it in front-end, but can't see any warnings when running `npm run dev`. For now, I added the logs and code for the context menu down the line.

Great job!!

Just make sure that your vscode is opening the `front-end` as workspace folder (instead of opening `320-S22-Track2` as workspace folder where `front-end` is a subfolder).

The error should be shown directly on the VSCode rather than on running `npm run dev`.

### The workspace folder should be opened like this:



### The formatting error should look like this:



If the Eslint is still not working properly, I can help you resolve it later this week.

**Comment by lilingxi01** [comment]
If the eslint is showing errors properly, you can then search "Eslint: Fix all auto-fixable problems" commands in vscode command palette to fix the formatting issue automatically.

You can also use terminal command `npm run lint -- -d [your_relative_folder_path]` to check all formatting issues of a specific directory, `npm run lint -- --file [your_relative_file_path]` to check it for a specific file, and add `--fix` at the end of above commands to fix all issues in selecting files.

For those "missing JsDoc" issues, you need to manually write the documentation for all javascript functions (this is part of the requirement of Google coding standard).

**Review by lilingxi01 — APPROVED** [review]
Nicely done!

**Pull request merged**
