### PR TITLE
Routing + Additional Dashboard UI Component/Functionality

### PR DESCRIPTION
**Pull request by emaohn**
Major addition in PR is the routing functionality
- Clicking different pages routes URL to corresponding pages
- Dashboard page is '/'
- Business process page is '/business-process/'
- Log events page is '/LogEvent/'

Additional features:
- Counts components
- Clicking SEE MORE button on counts/timelines routes to log events page
- Clicking on the timeline routes to log events page
- Timeline interactivity passes important parameters to log events page
- Donut charts, timelines, and counts component display data according to 20,000 fake data entries we created
- Dashboard is interactive with the timeframe dropdown
- Refresh button fetches latest data relative to timeframe

For filter passing between Dashboard --> Log Event page:
- LogEvent component can access through props by props.logEventFilters
- props.logEventFilters is a dictionary with attributes:
    start: Moment() object (inclusive)
    end: Moment() object (inclusive)
    type: 'severity' or 'priority'
    if type is severity --> severity: 'Error', 'Warning', or 'Logs' (Logs = all logs)

image

### CODE REVIEW

**Review by lilingxi01 — COMMENTED** [review]
It seems like some places are not linted. Don't forget to lint before merge.

**Review by ericlehmann17 — COMMENTED** [review]
Looks great

**Review by Phil-Nettekoven — DISMISSED** [review]
Looks good, great work!

**Comment by emaohn** [comment]
@Phil-Nettekoven Oops I just added a change to fix our lint errors--could you approve it again? Thanks!

**Review by ericlehmann17 — APPROVED** [review]

**Pull request merged**
