### PR TITLE
[Indigo] [Launchpad] Finish building launchpad session with mock data.

### LINKED ISSUE #61: [BPLaunchpad] Integrate the data-fetching module with TreeView and ActivityView.
# Functionality Checklist
- [x] Finish building the launchpad core module.
- [x] Integrate the launchpad hook at TreeView with mock data.
- [x] Integrate the launchpad hook with TreeFilter.
- [x] Integrate the launchpad hook at ActivityView with mock data.
- [x] ~~Integrate the launchpad hook with ActivityFilter.~~
  - This is moved to the next sprint.
- [x] Integrate both the TreeView and ActivityView to have a proper select-to-sync behavior.
  - When we select a business process instance in TreeView, the ActivityView will display all instances under the same business process.

### PR DESCRIPTION
**Pull request by lilingxi01**
# Expecting Functionalities
- [x] TreeView works with mock data in real time and also TreeFilter.
- [x] ActivityTable works with mock data in real time and also ActivityFilter.
- [x] Select-to-sync between TreeView and ActivityView.
- [x] Deal with any potential conflict.

### CODE REVIEW

**Comment by lilingxi01** [comment]
Conflict resolved.

**Comment by lilingxi01** [comment]
@nekomi2 I implemented the filter behavior, tree behavior, and also sync behavior (between tree view and activity table). The launchpad session configuration is located under the directory `./utils/business-process/launchpad/`. So when API is ready, we can simply put real web requests in there without changing a lot of front-end codes.

**Comment by nekomi2** [comment]
Getting a weird error with launchpad. 
image

**Review by nekomi2 — APPROVED** [review]
Great work.

**Pull request merged**
