### PR TITLE
Dashboard UI + Navigation Bar

### PR DESCRIPTION
**Pull request by emaohn**
Half completed dashboard UI with temporary placements for incomplete parts. 
Completed UI includes:

- Navigation Bar: changes view when tabs are clicked.
- Donut Charts: has some on-click functionality and hovering over shows values.
- Timelines: Has some on-click functionality to change view to log events and pass appropriate filters in. Hovering over shows the point value.

Temporary placements includes:
- Timeline selection drop down menu
- Displays with "counts" for certain types of logs x 4

Navigation Bar by default displays the Dashboard, but clicking the other tabs will change the view. Currently we just have blank divs with the appropriate text being displayed. However, once, this is merged in the other front-end teams can insert their views in place of those divs in the index.js file. 

image

### CODE REVIEW

**Review by Phil-Nettekoven — DISMISSED** [review]
Looks great! Glad to see the nav bar.

edit: Just make sure your code is eslint compliant, you can run npm run lint for a list of objections.

**Review by Phil-Nettekoven — DISMISSED** [review]
I think my last review went stale after there were changes to the branch. Looks good, just make sure your code passed eslint.

**Comment by emaohn** [comment]
@Phil-Nettekoven For the merge conflict in package.json I think we can just include everything from both sides. As for index.js, it seems like there's a button there from some other team for testing purposes to navigate to their view. We're introducing a navigation bar with our PR, so that button should be unnecessary. If desired, we can try to incorporate routing into our nav bar before merging this branch in.

**Comment by lilingxi01** [comment]
For conflict, I suggest you to merge `main` into `sesame-dev` first, and then deal with the conflict locally (by using a tool) and then push it back to the remote `sesame-dev`.

You do not have to manually merge two files (like copying and pasting all the time). In a good tool, you can just select both sides and get both content kept (for package.json). I used GitKraken to resolve the conflict, and there are many tools out there.

**Comment by Phil-Nettekoven** [comment]
@emaohn If you can get navigation before merging (at least for the views already on main), that would be ideal. Either way, I'll approve the PR after demos are done today. If you can't get navigation before that, it shouldn't be a big problem heading into the weekend. Thanks!

@lilingxi01 Thank you! I found that really helpful.

**Review by Phil-Nettekoven — APPROVED** [review]

**Pull request merged**
