### PR TITLE
Web Warriors - Log Event Styling + Component Changes

### PR DESCRIPTION
**Pull request by ericlehmann17**
- Updated styling of the log event page to look more consistent with other views. 
- Replaced our dropdown and date picker components with BPDomainSelector and BPDatePicker components respectively (for consistency and improved functionality)
- Other minor fixes and changes related to customer requests.

Current state of our Log Events View:
image

Current state of our Log Detail View (example):
image

### CODE REVIEW

**Comment by lilingxi01** [comment]
Login Page is generating an error in browser console.

CleanShot 2022-04-21 at 00 04 01@2x

**Comment by lilingxi01** [comment]
It seems like your `components` (lowercase `C`) folder is named `Components` (uppercase `C`). Git will not differ the casing, so it works just fine, but generating warnings in the terminal (and probably future confusions). Do you want to refactor your folder name from `Components` to `components`?

**Terminal:**
CleanShot 2022-04-21 at 00 07 46@2x

**Comment by lilingxi01** [comment]
And some of your files are not passing the eslint, please make sure to fix them (you can automatically fix them, but be careful do not fix other teams' files which may generate potential conflicts).

For linting, you can run `npm run lint` to list all errors or check https://github.com/david-fisher/320-S22-Track2/pull/50#issuecomment-1073357503 if you have no idea.

CleanShot 2022-04-21 at 00 10 58@2x

**Review by lilingxi01 — DISMISSED** [review]
Please be sure to lint. Check this: https://github.com/david-fisher/320-S22-Track2/pull/155#issuecomment-1104688878

**Comment by ericlehmann17** [comment]
@lilingxi01 Just made a commit fixing linting errors in WebWarriors components and the _app.js file. Also refactored Components to components as requested, let me know if there are any other glaring problems that I need to fix before merge (or if I missed anything).

**Review by emaohn — DISMISSED** [review]
lgtm

**Review by emaohn — APPROVED** [review]

**Pull request merged**
